# Generated by Django 4.0.5 on 2022-06-27 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 2, 3, 40, 206963)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('doing', 'doing'), ('pending', 'pending')], max_length=25),
        ),
    ]
