  version: '3.9'


  services:
    backend:
      container_name: backend_teste
      build: .
      ports: 
      - "3001:3001"
      volumes:
      - '.:/back'
      depends_on:
        - "mongo"

    mongo:
      container_name: mongoDB_exer
      image: mongo:4.4-focal
      ports: 
      - "27017:27017"
      restart: always